sequenceDiagram
    autonumber
    actor U as User
    participant S as System
    participant SMTP as SMTP Mail Server

    U->>S: requests to view the list of users
    alt User do not have permission to view the users
    S-->>U: Redirect to the login page
    end
    S-->>U: returns the list of users

    U->>S: Click the user in the user index page
    
    alt User do not have permission to view user
    S-->>U: Redirect to the users index page
    end

    S-->>U: returns the details of the users
    U->>S: Click the Add Send Reset Password email button

    S->>SMTP: Send the Reset Password email
    SMTP-->>S: returns the email sent

    S-->>U: returns the email sent
