sequenceDiagram
    autonumber
    actor U as User
    participant S as System

    U->>S: requests to view the list of models
    alt User do not have permission to view the models
    S-->>U: Redirect to the login page
    end
    S-->>U: returns the list of models

    U->>S: Click the model record in the model index page
    
    alt User do not have permission to view the model
    S-->>U: Redirect to the model index page
    end

    S-->>U: returns the details of the model
    U->>S: Click the Audit Trail button in the model details page

    alt User do not have permission to audit
    S-->>U: Redirect to the model index page
    end

    S-->>U: returns the audit information of the model
