name: Check & fix styling

on: [ push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes

      - name: Install node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run Blade formatter
        run: |
          npm install -g blade-formatter
          sleep 10
          blade-formatter --write resources/**/*.blade.php
          sleep 30

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
