on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Setup .env file
        run: |
          cp .env.ci .env

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan --version

      - name: Migrate database
        run: |
          mysql --version
          php artisan migrate:fresh --seed

      - name: Execute tests
        run: vendor/bin/phpunit
